/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.penjualan.cd;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Muhammad Alqi
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        //Membuat form tidak dapat diubah ukurannya
        /*new MenuUtama().setExtendedState(JFrame.MAXIMIZED_BOTH);
        new MenuUtama().setVisible(true);
        new MenuUtama().setResizable(false);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        version = new javax.swing.JLabel();
        tombolMetal = new javax.swing.JLabel();
        tombolHipHop = new javax.swing.JLabel();
        tombolJazz = new javax.swing.JLabel();
        tombolPop = new javax.swing.JLabel();
        tombolTentangKami1 = new javax.swing.JLabel();
        tombolTentangKami = new javax.swing.JLabel();
        tombolFaktur = new javax.swing.JLabel();
        tombolDataPembeli = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        version.setForeground(new java.awt.Color(255, 255, 255));
        version.setText("Application v 1.0");
        jPanel1.add(version);
        version.setBounds(20, 550, 110, 14);

        tombolMetal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolMetal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolMetalMouseClicked(evt);
            }
        });
        jPanel1.add(tombolMetal);
        tombolMetal.setBounds(480, 350, 150, 210);

        tombolHipHop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolHipHop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolHipHopMouseClicked(evt);
            }
        });
        jPanel1.add(tombolHipHop);
        tombolHipHop.setBounds(300, 350, 150, 210);

        tombolJazz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolJazz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolJazzMouseClicked(evt);
            }
        });
        jPanel1.add(tombolJazz);
        tombolJazz.setBounds(300, 120, 150, 210);

        tombolPop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolPop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolPopMouseClicked(evt);
            }
        });
        jPanel1.add(tombolPop);
        tombolPop.setBounds(480, 120, 150, 210);

        tombolTentangKami1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolTentangKami1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolTentangKami1MouseClicked(evt);
            }
        });
        jPanel1.add(tombolTentangKami1);
        tombolTentangKami1.setBounds(0, 390, 240, 40);

        tombolTentangKami.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolTentangKami.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolTentangKamiMouseClicked(evt);
            }
        });
        jPanel1.add(tombolTentangKami);
        tombolTentangKami.setBounds(0, 330, 240, 40);

        tombolFaktur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolFaktur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolFakturMouseClicked(evt);
            }
        });
        jPanel1.add(tombolFaktur);
        tombolFaktur.setBounds(0, 270, 240, 40);

        tombolDataPembeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolDataPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolDataPembeliMouseClicked(evt);
            }
        });
        jPanel1.add(tombolDataPembeli);
        tombolDataPembeli.setBounds(0, 210, 240, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menuutama.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 931, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tombolDataPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolDataPembeliMouseClicked
        new tabelPembeli().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolDataPembeliMouseClicked

    private void tombolFakturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolFakturMouseClicked
        new Faktur().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolFakturMouseClicked

    private void tombolTentangKamiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolTentangKamiMouseClicked
        new aboutUs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolTentangKamiMouseClicked

    private void tombolPopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPopMouseClicked
        new pop().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolPopMouseClicked

    private void tombolJazzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolJazzMouseClicked
        new jazz().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolJazzMouseClicked

    private void tombolHipHopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolHipHopMouseClicked
        new hiphop().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolHipHopMouseClicked

    private void tombolMetalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolMetalMouseClicked
        new metal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolMetalMouseClicked

    private void tombolTentangKami1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolTentangKami1MouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolTentangKami1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tombolDataPembeli;
    private javax.swing.JLabel tombolFaktur;
    private javax.swing.JLabel tombolHipHop;
    private javax.swing.JLabel tombolJazz;
    private javax.swing.JLabel tombolMetal;
    private javax.swing.JLabel tombolPop;
    private javax.swing.JLabel tombolTentangKami;
    private javax.swing.JLabel tombolTentangKami1;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
