/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.penjualan.cd;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Kelompok 1 - Penjualan CD
 */
public class MenuPembeli extends javax.swing.JFrame {
    
   private boolean databaru;
   public final Koneksi koneksi = new Koneksi();
   
    /**
     * Creates new form MenuPembeli
     */
    public MenuPembeli() {
        initComponents();
         getData();
    databaru = true; 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JKodePembeli = new javax.swing.JTextField();
        JNama = new javax.swing.JTextField();
        JPekerjaan = new javax.swing.JTextField();
        JAlamat = new javax.swing.JTextField();
        JNoTelepon = new javax.swing.JTextField();
        ButtonBersihkan = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelData = new javax.swing.JTable();
        ButtonHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Pembeli");

        jLabel2.setText("Nama");

        jLabel3.setText("Pekerjaan");

        jLabel4.setText("Alamat");

        jLabel5.setText("No. Telepon");

        ButtonBersihkan.setText("RESET");
        ButtonBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBersihkanActionPerformed(evt);
            }
        });

        ButtonEdit.setText("EDIT");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonTambah.setText("SIMPAN");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        TabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Pembeli", "Nama", "Pekerjaan", "Alamat", "No. Telepon"
            }
        ));
        TabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelData);

        ButtonHapus.setText("HAPUS");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariKeyTyped(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCari)
                                    .addComponent(JKodePembeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(JNama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JNoTelepon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JPekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari))
                            .addComponent(JAlamat))))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnKembali)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JKodePembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(13, 13, 13)
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTambah)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonBersihkan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private DefaultTableModel tabmode;
    
    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
 try {
                databaru = true;
                String sql = "INSERT INTO db_pembeli VALUES('%s', '%s', '%s', '%s', '%s')";
                
                sql = String.format(
                        sql,
                        JKodePembeli.getText(),
                        JNama.getText(),
                        JPekerjaan.getText(),
                        JAlamat.getText(),
                        JNoTelepon.getText()
                );
                
                Connection conn = koneksi.getKoneksi();
                PreparedStatement pst = conn.prepareStatement (sql);
                
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal Disimpan" + ex);
            }
        getData ();                                      
    }//GEN-LAST:event_ButtonTambahActionPerformed
                              
    
    private void ButtonBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBersihkanActionPerformed
        databaru = true;
        JKodePembeli.setText("");
        JNama.setText("");
        JPekerjaan.setText("");
        JAlamat.setText("");
        JNoTelepon.setText("");
    }//GEN-LAST:event_ButtonBersihkanActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        try {
            String sql  = "DELETE FROM db_pembeli WHERE kodePembeli='" + JKodePembeli.getText() + "'";
            
            Connection conn = koneksi.getKoneksi();
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
            ButtonBersihkanActionPerformed(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Dihapus" + ex);
        }
        
        getData();
                                      
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
 try {
                databaru = true;
                String sql = "UPDATE db_pembeli SET nama = '%s', pekerjaan = '%s', alamat = '%s', noTelepon = '%s' WHERE kodePembeli = '%s'";
                
                sql = String.format(
                        sql,
                        JNama.getText(),
                        JPekerjaan.getText(),
                        JAlamat.getText(),
                        JNoTelepon.getText(), 
                        JKodePembeli.getText()
                        
                );
                
                JOptionPane.showMessageDialog(null, "Berhasil Diubah");
                
                Connection conn = koneksi.getKoneksi();
                PreparedStatement pst = conn.prepareStatement (sql);
                
                pst.execute();
                
                
                
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal Diubah" + ex);
            }
                getData();    
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void TabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataMouseClicked
         try{
            databaru = false;
            int row = TabelData.getSelectedRow();
            String kodePembeli = TabelData.getModel().getValueAt(row,0).toString();
            
            Connection conn = koneksi.getKoneksi();
            Statement stm = conn.createStatement();
            ResultSet sql = stm.executeQuery("SELECT * FROM db_pembeli WHERE kodePembeli='" + kodePembeli + "'");
            
            if (sql.next()){
                JKodePembeli.setText(sql.getString("kodePembeli"));
                JNama.setText(sql.getString("nama"));
                JPekerjaan.setText(sql.getString("pekerjaan"));
                JAlamat.setText(sql.getString("alamat"));
                JNoTelepon.setText(sql.getString("noTelepon"));
            
            }
        } catch (SQLException ex){
            Logger.getLogger(MenuPembeli.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_TabelDataMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String sqlPencarian = "select * from db_pembeli where kodePembeli like '%" + txtCari.getText() + "%' or "
        + "nama like '%" + txtCari.getText() + "%' or "
        + "pekerjaan like '%" + txtCari.getText() + "%' or "
        + "alamat like '%" + txtCari.getText() + "%' or "
        + "noTelepon like '%" + txtCari.getText() + "%'";
        pencarian(sqlPencarian);
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyTyped
        String sqlPencarian = "select * from db_pembeli where kodePembeli like '%" + txtCari.getText() + "%' or "
        + "nama like '%" + txtCari.getText() + "%' or "
        + "pekerjaan like '%" + txtCari.getText() + "%' or "
        + "alamat like '%" + txtCari.getText() + "%' or "
        + "noTelepon like '%" + txtCari.getText() + "%'";
        pencarian(sqlPencarian);
    }//GEN-LAST:event_txtCariKeyTyped

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.toBack();
        MenuUtama mp = new MenuUtama();
        mp.setVisible(true);
        mp.toFront();
    }//GEN-LAST:event_btnKembaliActionPerformed
//    
//    public void lebarKolom() {
//        TableColumn kolom;
//        TabelData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
//        kolom = TabelData.getColumnModel().getColumn(0);
//        kolom.setPreferredWidth(40);
//        kolom = TabelData.getColumnModel().getColumn(1);
//        kolom.setPreferredWidth(100);
//        kolom = TabelData.getColumnModel().getColumn(2);
//        kolom.setPreferredWidth(100);
//        kolom = TabelData.getColumnModel().getColumn(3);
//        kolom.setPreferredWidth(120);
//        kolom = TabelData.getColumnModel().getColumn(4);
//        kolom.setPreferredWidth(130);
//    }
    
    
    public void dataTable() {
        Object[] Baris = {"Kode Pembeli", "Nama", "Pekerjaan", "Alamat", "No Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        TabelData.setModel(tabmode);
        String sql = "select * from db_pembeli order by kodePembeli asc";
        try {
            Connection conn = koneksi.getKoneksi();
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String ID = hasil.getString("ID");
                String kodePembeli = hasil.getString("kodePembeli");
                String nama = hasil.getString("nama");
                String pekerjaan = hasil.getString("pekerjaan");
                String alamat = hasil.getString("alamat");
                String noTelepon = hasil.getString("noTelepon");
                String[] data = {kodePembeli, nama, pekerjaan, alamat, noTelepon};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }
    
    public void pencarian(String sql) {
        Object[] Baris = {"Kode Pembeli", "Nama", "Pekerjaan", "Alamat", "No Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        TabelData.setModel(tabmode);
        int brs = TabelData.getRowCount();
        for (int i = 0; 1 < brs; i++) {
            tabmode.removeRow(1);
        }
        try {
            Connection conn = koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            ResultSet hasil = stm.executeQuery(sql);
            while (hasil.next()) {
                String kodePembeli = hasil.getString("kodePembeli");
                String nama = hasil.getString("nama");
                String pekerjaan = hasil.getString("pekerjaan");
                String alamat = hasil.getString("alamat");
                String noTelepon = hasil.getString("noTelepon");
                String[] data = {kodePembeli, nama, pekerjaan, alamat, noTelepon};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
        
        
    }
    
//    public void noTable() {
//        int Baris = tabmode.getRowCount();
//        for (int a = 0; a < Baris; a++) {
//            String nomor = String.valueOf(a + 1);
//            tabmode.setValueAt(nomor + ".", a, 0);
//        }
//    }
    
    private void getData(){
        try {
            Connection conn =koneksi.getKoneksi();
            Statement stm = conn.createStatement();
            ResultSet result = stm.executeQuery("SELECT * FROM db_pembeli");
            
            DefaultTableModel model = (DefaultTableModel) TabelData.getModel();
            
            model.setRowCount (0); //reset data table
            
            while (result.next()){
                String kode = result.getString ("kodePembeli");
                String nama = result.getString ("nama");
                String pekerjaan = result.getString ("pekerjaan");
                String alamat = result.getString ("alamat");
                String no = result.getString ("noTelepon");
                
               model.addRow(new Object []{kode, nama, pekerjaan, alamat, no});
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPembeli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBersihkan;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JTextField JAlamat;
    private javax.swing.JTextField JKodePembeli;
    private javax.swing.JTextField JNama;
    private javax.swing.JTextField JNoTelepon;
    private javax.swing.JTextField JPekerjaan;
    private static javax.swing.JTable TabelData;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
